---
title: "Biomass"
format: html
---

{{< include ../_data.qmd >}}

## Function: `getDomainBiomass()`

### Purpose

Calculates mean biomass kg/cylinder (or $kg/177m^2$) at the domain level.

### Usage

```{r}
#| echo: true
#| eval: false
getDomainBiomass()
```

### Output

```{r}
#| echo: true
#| warning: FALSE
getDomainBiomass(STTSTJ, "spa viri") %>% 
  select(YEAR:n) %>% 
  kableExtra::kable()
```

## Function: `getStratumBiomass()`

### Purpose

Calculates mean biomass kg/cylinder (or $kg/177m^2$) at the stratum level.

### Usage

```{r}
#| echo: true
#| eval: false
getStratumBiomass()
```

### Output

```{r}
#| echo: true
#| warning: FALSE
getStratumBiomass(STTSTJ, "spa viri") %>% 
  select(YEAR:n) %>% 
  kableExtra::kable()
```

## Function: `getPSUBiomass()`

### Purpose

Calculates mean biomass kg/cylinder (or $kg/177m^2$) at the Primary Sample Unit (PSU) level.

### Usage

```{r}
#| echo: true
#| eval: false
getPSUBiomass()
```

### Output

```{r}
#| echo: true
#| warning: FALSE
getPSUBiomass(STTSTJ, "spa viri") %>%
  head() %>% 
  kableExtra::kable()
```
